######################################################################
# Automatically generated by qmake (3.0) Sun May 19 21:46:39 2013
######################################################################

TEMPLATE = app
TARGET = find
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
QT   += widgets


