######################################################################
# Automatically generated by qmake (3.0) Tue May 21 21:01:10 2013
######################################################################

TEMPLATE = app
TARGET = my
INCLUDEPATH += .

# Input
FORMS += untitled.ui
SOURCES += main.cpp
QT += widgets

